In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [22]:
df1 = pd.read_csv("./Social_Network_Ads.csv")

In [23]:
df1.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [25]:
df2 = df1.iloc[:, 2:]
df2.head()

   Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [27]:
df2.sample(5)

     Age  EstimatedSalary  Purchased
35    35            27000          0
174   34            72000          0
383   49            28000          1
336   58           144000          1
74    32            18000          0

In [28]:
df2.tail(5)

     Age  EstimatedSalary  Purchased
395   46            41000          1
396   51            23000          1
397   50            20000          1
398   36            33000          0
399   49            36000          1

In [31]:
!pip install scikit-learn

Collecting scikit-learn
  Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.24.1 in .\Day26_Database\mongo\Lib\site-packages (from scikit-learn) (2.4.2)
Requirement already satisfied: scipy>=1.10.0 in .\Day26_Database\mongo\Lib\site-packages (from scikit-learn) (1.17.1)
Collecting joblib>=1.3.0 (from scikit-learn)
  Using cached joblib-1.5.3-py3-none-any.whl.metadata (5.5 kB)
Collecting threadpoolctl>=3.2.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Using cached scikit_learn-1.8.0-cp311-cp311-win_amd64.whl (8.1 MB)
Using cached joblib-1.5.3-py3-none-any.whl (309 kB)
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, joblib, scikit-learn

   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   ------------- -------------------------- 1/3 [joblib]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   -------------------------- ------------- 2/3 [scikit-learn]
   ---------------------------------------- 3/3 [scikit-learn]

Successfully installed joblib-1.5.3 scikit-learn-1.8.0 threadpoolctl-3.6.0

In [32]:
# Scaling the data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df2.drop("Purchased", axis=1), df2["Purchased"], test_size=0.3, random_state=42)

In [34]:
X_train.shape, X_test.shape

((280, 2), (120, 2))

In [ ]:
X_train.head(3)
# x data are the input features

     Age  EstimatedSalary
157   29            75000
109   38            80000
17    45            26000

In [ ]:
y_train.head(3)
# y data are the target feature

157    0
109    0
17     1
Name: Purchased, dtype: int64

standardScaler

In [40]:
from sklearn.preprocessing import StandardScaler
standardScaler = StandardScaler()

# fit the scaler to the training data, it will learn parameters
standardScaler.fit(X_train)

# transform train and test data
X_train_scaled = standardScaler.transform(X_train)
X_test_scaled = standardScaler.transform(X_test)

In [41]:
standardScaler.mean_

array([3.75750000e+01, 7.05892857e+04])

In [ ]:
X_train_scaled
# converted to numpy array, we can convert it back to dataframe if we want

array([[-0.84252154,  0.1301563 ],
       [ 0.04175763,  0.2777019 ],
       [ 0.72953032, -1.31579061],
       [ 1.61380949,  1.10395728],
       [ 0.82778356, -1.40431797],
       [-1.43204099, -1.25677236],
       [-0.05649561,  0.1301563 ],
       [ 0.43477059, -0.16493491],
       [-0.2530021 ,  0.01211982],
       [ 1.31904976,  2.22530386],
       [ 0.14001087,  0.74984783],
       [-1.33378775,  0.54328399],
       [ 2.00682245,  0.72033871],
       [-1.23553451, -1.43382709],
       [ 0.33651735, -0.34198963],
       [-0.94077478,  0.54328399],
       [ 0.43477059,  0.2777019 ],
       [ 0.43477059,  1.10395728],
       [ 0.82778356,  0.74984783],
       [ 0.9260368 ,  1.25150288],
       [-0.44950858, -1.25677236],
       [-1.82505395, -1.34529973],
       [ 1.12254328,  0.54328399],
       [-0.64601506, -1.64039093],
       [-0.7442683 ,  0.24819278],
       [ 1.02429004,  2.07775825],
       [-0.54776182,  1.36953936],
       [-0.05649561,  0.01211982],
       [-1.9233072 ,  0.45475663],
       [ 0.43477059,  0.24819278],
       [-1.03902802,  0.39573838],
       [ 0.23826411, -0.16493491],
       [ 1.90856921,  0.10064718],
       [-1.13728127, -1.64039093],
       [-1.13728127,  0.2777019 ],
       [-0.84252154, -0.81413556],
       [-0.44950858,  2.31383122],
       [ 0.14001087, -0.84364468],
       [ 1.61380949,  0.98592079],
       [-0.15474885, -1.10922676],
       [ 0.82778356, -1.13873588],
       [ 0.23826411,  2.10726737],
       [-0.05649561, -0.25346227],
       [-0.84252154,  2.2843221 ],
       [-0.05649561, -0.40100787],
       [-0.2530021 , -0.60757171],
       [ 0.43477059, -0.51904435],
       [-0.2530021 , -0.96168116],
       [ 0.33651735, -1.19775412],
       [ 0.23826411,  0.04162894],
       [-1.13728127, -1.64039093],
       [-0.64601506, -0.07640754],
       [-0.2530021 , -0.51904435],
       [-0.2530021 , -1.34529973],
       [-0.7442683 ,  0.54328399],
       [ 0.33651735,  0.04162894],
       [-0.94077478,  1.54659408],
       [ 0.82778356,  0.33672014],
       [-1.53029423, -0.22395315],
       [ 0.72953032, -1.43382709],
       [-0.7442683 , -0.63708083],
       [-0.35125534, -1.34529973],
       [ 0.23826411,  0.1301563 ],
       [-0.54776182,  1.36953936],
       [-1.43204099,  0.33672014],
       [-1.13728127,  0.2777019 ],
       [ 1.02429004,  1.78266705],
       [ 2.10507569,  2.13677649],
       [-0.2530021 , -0.46002611],
       [-0.35125534, -0.81413556],
       [ 0.14001087, -0.28297139],
       [-1.03902802,  0.74984783],
       [ 2.20332893,  0.36622926],
       [-1.33378775, -0.46002611],
       [ 2.00682245,  2.16628562],
       [ 1.51555624,  0.98592079],
       [-0.2530021 ,  0.24819278],
       [-0.15474885,  0.83837519],
       [ 1.90856921, -0.31248051],
       [-0.05649561,  1.95972177],
       [-0.44950858, -0.81413556],
       [ 0.33651735,  0.01211982],
       [ 1.417303  , -1.46333621],
       [ 1.417303  ,  2.34334034],
       [-0.05649561, -0.0173893 ],
       [-1.13728127,  0.39573838],
       [-1.13728127,  0.04162894],
       [-1.13728127, -0.54855347],
       [ 0.33651735, -0.31248051],
       [-0.64601506, -0.13542579],
       [-0.05649561,  2.16628562],
       [ 0.04175763, -0.28297139],
       [-0.64601506, -1.07971764],
       [ 0.43477059,  0.1301563 ],
       [ 0.82778356,  1.36953936],
       [-0.15474885, -0.54855347],
       [ 0.04175763,  0.01211982],
       [ 1.12254328,  0.51377487],
       [ 1.90856921, -1.10922676],
       [ 1.02429004,  1.98923089],
       [ 0.9260368 , -0.60757171],
       [-0.44950858, -0.04689842],
       [-0.05649561,  2.22530386],
       [-1.72680071,  0.33672014],
       [ 0.23826411, -0.69609908],
       [-0.2530021 , -1.43382709],
       [-1.72680071, -1.0206994 ],
       [ 0.72953032, -0.75511732],
       [-1.13728127, -0.81413556],
       [ 2.00682245,  0.89739343],
       [ 0.23826411, -0.40100787],
       [ 0.04175763,  1.22199376],
       [-0.05649561,  0.2777019 ],
       [ 1.12254328, -1.25677236],
       [-0.15474885,  0.1301563 ],
       [ 0.33651735,  0.04162894],
       [-0.2530021 , -0.31248051],
       [ 0.53302383,  1.72364881],
       [ 0.33651735,  0.48426575],
       [ 0.04175763,  1.25150288],
       [ 2.00682245, -1.40431797],
       [-1.13728127, -1.13873588],
       [-0.54776182, -1.55186357],
       [ 0.33651735, -0.54855347],
       [-0.64601506, -1.55186357],
       [-0.2530021 ,  0.51377487],
       [ 1.02429004, -1.05020852],
       [-1.03902802,  0.54328399],
       [-0.2530021 ,  0.77935695],
       [ 0.43477059,  0.07113806],
       [-1.62854747, -0.07640754],
       [ 0.33651735,  0.04162894],
       [-0.44950858, -0.31248051],
       [ 0.14001087,  1.87119441],
       [-0.94077478,  0.39573838],
       [ 0.82778356,  0.51377487],
       [-1.33378775, -0.37149875],
       [-0.64601506,  1.39904848],
       [ 1.22079652,  0.51377487],
       [-1.72680071,  0.33672014],
       [-0.54776182,  1.90070353],
       [-1.72680071,  0.45475663],
       [-0.2530021 , -1.28628149],
       [-0.84252154, -0.81413556],
       [-1.62854747,  0.51377487],
       [-0.2530021 , -0.34198963],
       [ 0.72953032, -1.13873588],
       [ 2.20332893, -0.84364468],
       [-0.2530021 ,  0.60230223],
       [-0.2530021 , -0.78462644],
       [-1.9233072 , -0.78462644],
       [ 0.43477059,  2.31383122],
       [ 0.72953032,  0.24819278],
       [ 0.23826411, -0.31248051],
       [-1.33378775, -1.40431797],
       [-0.44950858, -0.57806259],
       [ 0.43477059, -0.0173893 ],
       [ 1.71206273,  1.75315793],
       [ 1.22079652, -0.78462644],
       [ 1.02429004,  1.4285576 ],
       [-1.82505395,  0.15966542],
       [ 0.33651735,  0.04162894],
       [ 0.23826411,  0.01211982],
       [-1.03902802,  0.51377487],
       [-0.15474885,  1.63512145],
       [-0.2530021 ,  0.1301563 ],
       [-0.2530021 , -0.37149875],
       [-0.35125534,  1.31052112],
       [-0.2530021 ,  0.07113806],
       [ 2.20332893,  1.10395728],
       [-1.23553451,  0.48426575],
       [-1.03902802, -0.48953523],
       [-1.62854747, -1.61088181],
       [-0.05649561,  0.10064718],
       [-0.2530021 , -0.93217204],
       [ 1.61380949, -0.0173893 ],
       [ 0.9260368 , -1.19775412],
       [ 0.04175763, -0.60757171],
       [-0.2530021 ,  2.25481298],
       [-0.2530021 ,  0.18917454],
       [ 0.33651735,  0.24819278],
       [-0.05649561, -1.10922676],
       [ 2.20332893, -0.7256082 ],
       [-0.94077478, -0.34198963],
       [-1.43204099, -0.13542579],
       [-1.43204099, -0.22395315],
       [-0.7442683 , -1.58137269],
       [-1.23553451, -1.10922676],
       [ 2.10507569,  0.36622926],
       [ 2.00682245, -0.96168116],
       [-1.9233072 ,  0.33672014],
       [ 0.82778356, -0.34198963],
       [-1.03902802, -1.58137269],
       [ 2.00682245, -0.69609908],
       [ 1.02429004, -1.19775412],
       [ 1.12254328, -0.16493491],
       [ 1.22079652, -1.0206994 ],
       [ 1.51555624,  0.04162894],
       [ 0.23826411, -0.40100787],
       [ 1.417303  ,  1.281012  ],
       [ 2.10507569, -0.84364468],
       [-0.15474885, -0.22395315],
       [ 0.43477059,  0.98592079],
       [-0.05649561, -0.54855347],
       [ 1.02429004, -1.10922676],
       [ 2.10507569, -1.22726324],
       [-0.05649561,  0.24819278],
       [ 0.23826411, -0.28297139],
       [ 1.12254328,  0.10064718],
       [-1.23553451,  0.57279311],
       [-0.7442683 , -1.64039093],
       [ 0.23826411,  0.21868366],
       [-1.33378775,  0.39573838],
       [ 0.04175763, -0.60757171],
       [ 0.72953032,  1.78266705],
       [-1.62854747,  0.04162894],
       [-0.2530021 , -1.40431797],
       [-0.2530021 , -1.49284533],
       [-0.64601506,  0.54328399],
       [-0.7442683 ,  0.2777019 ],
       [ 0.9260368 , -0.69609908],
       [-1.03902802,  0.57279311],
       [-0.2530021 ,  0.04162894],
       [-0.7442683 ,  1.34003024],
       [ 0.14001087,  1.51708496],
       [-0.84252154,  0.36622926],
       [ 0.33651735, -0.22395315],
       [ 1.02429004,  0.57279311],
       [ 0.04175763, -0.34198963],
       [-0.54776182, -1.55186357],
       [ 0.14001087,  0.1301563 ],
       [-1.13728127,  0.30721102],
       [ 0.14001087,  1.04493904],
       [-1.53029423, -0.46002611],
       [-0.15474885,  1.39904848],
       [ 2.20332893, -0.84364468],
       [-0.94077478, -0.46002611],
       [ 1.31904976,  1.87119441],
       [ 1.12254328, -1.25677236],
       [-0.15474885, -0.31248051],
       [ 1.81031597,  0.98592079],
       [-1.03902802, -0.37149875],
       [-1.33378775, -1.13873588],
       [-0.35125534,  0.04162894],
       [-0.94077478, -1.13873588],
       [ 1.22079652, -1.49284533],
       [-0.44950858, -0.8731538 ],
       [-0.84252154, -0.69609908],
       [-1.53029423, -1.55186357],
       [-0.7442683 ,  1.90070353],
       [ 0.9260368 ,  1.01542992],
       [ 0.82778356,  0.24819278],
       [ 1.02429004,  1.87119441],
       [ 0.9260368 , -0.63708083],
       [ 1.12254328,  2.07775825],
       [-0.54776182,  0.86788431],
       [ 0.04175763,  0.01211982],
       [-1.82505395, -1.31579061],
       [-0.05649561,  0.18917454],
       [ 0.9260368 , -0.57806259],
       [ 0.23826411, -0.40100787],
       [-0.15474885,  1.60561233],
       [-1.72680071,  0.10064718],
       [-0.64601506, -0.37149875],
       [ 0.33651735, -0.75511732],
       [ 0.43477059, -0.48953523],
       [-0.94077478, -0.99119028],
       [ 0.14001087,  0.07113806],
       [-0.94077478,  0.4252475 ],
       [ 0.04175763, -0.57806259],
       [ 0.9260368 , -0.81413556],
       [-0.05649561,  0.04162894],
       [ 1.12254328, -1.0206994 ],
       [ 0.72953032, -1.43382709],
       [-0.2530021 ,  0.04162894],
       [-1.33378775, -1.28628149],
       [-1.13728127, -1.05020852],
       [ 0.53302383,  1.84168529],
       [ 0.14001087,  0.18917454],
       [-0.54776182,  0.45475663]])

In [43]:
X_train_scaled=pd.DataFrame(X_train_scaled, columns=X_train.columns)
X_test_scaled=pd.DataFrame(X_test_scaled, columns=X_test.columns)

In [44]:
X_train_scaled

          Age  EstimatedSalary
0   -0.842522         0.130156
1    0.041758         0.277702
2    0.729530        -1.315791
3    1.613809         1.103957
4    0.827784        -1.404318
..        ...              ...
275 -1.333788        -1.286281
276 -1.137281        -1.050209
277  0.533024         1.841685
278  0.140011         0.189175
279 -0.547762         0.454757

[280 rows x 2 columns]

In [45]:
X_train.describe()

              Age  EstimatedSalary
count  280.000000       280.000000
mean    37.575000     70589.285714
std     10.196005     33948.504534
min     18.000000     15000.000000
25%     30.000000     44000.000000
50%     37.000000     71000.000000
75%     45.000000     88000.000000
max     60.000000    150000.000000

In [46]:
np.round(X_train.describe(), 2)

          Age  EstimatedSalary
count  280.00           280.00
mean    37.58         70589.29
std     10.20         33948.50
min     18.00         15000.00
25%     30.00         44000.00
50%     37.00         71000.00
75%     45.00         88000.00
max     60.00        150000.00

In [ ]:
np.round(X_train_scaled.describe(), 2)
# after scaling, the mean is 0 and std is 1 for all features, this is what standardization does.

          Age  EstimatedSalary
count  280.00           280.00
mean    -0.00             0.00
std      1.00             1.00
min     -1.92            -1.64
25%     -0.74            -0.78
50%     -0.06             0.01
75%      0.73             0.51
max      2.20             2.34

Effect of Scaling on the data